services:
  - type: web
    name: greekmetrics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: OFFICER_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
